<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>An Akka Persistence Module for SQL Databases using Linq2Db.</Description>
    <TargetFrameworks>$(NetStandardLibVersion);$(NetLibVersion)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Persistence.Query" />
    <PackageReference Include="Akka.Streams" />
    <PackageReference Include="LanguageExt.Core" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <!--<PackageReference Include="linq2db" />-->
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Reactive.Linq" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="persistence.conf" CopyToOutputDirectory="Always" />
    <EmbeddedResource Include="snapshot.conf" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="linq2db">
      <HintPath>..\..\..\linq2db\.build\bin\LinqToDB\release\netstandard2.0\linq2db.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\linq2db\.build\bin\LinqToDB\release\netstandard2.0\linq2db.dll" CopyToOutputDirectory="Always" />
  </ItemGroup>
  
</Project>
