akka {

    persistence {
        journal {
            plugin = "akka.persistence.journal.sql"
			sql {
				provider-name = "SqlServer"
                class = "Akka.Persistence.Sql.Journal.SqlWriteJournal, Akka.Persistence.Sql"
				connection-string = "Data Source=localhost;Initial Catalog=TitaniumDLMS.Persistence;Integrated Security=True;Encrypt=False"
                serializer = hyperion
                #tag-write-mode = Csv
                default {
                    schema-name = dbo
                    journal {
                        table-name = "OPE_EVENTJOURNAL"
                        columns {
                            ordering = Ordering
                            deleted = IsDeleted
                            persistence-id = PersistenceId
                            sequence-number = SequenceNr
                            created = Timestamp
                            tags = Tags
                            message = Payload
                            identifier = SerializerId
                            manifest = Manifest
                            writer-uuid = WriterId
                        }
                    }
                    metadata {
                        table-name = "OPE_METADATA"
                        columns {
                            persistence-id = PersistenceId
                            sequence-number = SequenceNr
                        }
                    }
                }
			}
        }
		query.journal {
            sql {
			    provider-name = "SqlServer"
                class = "Akka.Persistence.Sql.Query.SqlReadJournalProvider, Akka.Persistence.Sql"
				connection-string = "Data Source=localhost;Initial Catalog=TitaniumDLMS.Persistence;Integrated Security=True;Encrypt=False"
                serializer = hyperion
                #tag-read-mode = Csv
                default = ${akka.persistence.journal.sql.default}
            }
		}
	}
}
