<Project>
  <PropertyGroup>
    <VersionPrefix>1.5.70.1</VersionPrefix>
    <PackageReleaseNotes>**Dependency Correction**

* Correct the prerelease Akka.NET package dependencies in `1.5.70` to stable `1.5.70`.
* Upgrade Akka.Hosting package dependencies from `1.5.67` to stable `1.5.70`.</PackageReleaseNotes>
  </PropertyGroup>
</Project>